USE [master]
GO

/****** Object:  Database [AssetManager]    Script Date: 8/24/2020 11:30:42 AM ******/
CREATE DATABASE [AssetManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AssetManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AssetManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AssetManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AssetManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AssetManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AssetManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AssetManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AssetManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AssetManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AssetManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [AssetManager] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AssetManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AssetManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AssetManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AssetManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AssetManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AssetManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AssetManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AssetManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AssetManager] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AssetManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AssetManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AssetManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AssetManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AssetManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AssetManager] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AssetManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AssetManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AssetManager] SET  MULTI_USER 
GO

ALTER DATABASE [AssetManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AssetManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AssetManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AssetManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AssetManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AssetManager] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AssetManager] SET  READ_WRITE 
GO

