// <auto-generated />
using CPRG214.AssetManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.AssetManager.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    [Migration("20200730182022_CreateAssetManager")]
    partial class CreateAssetManager
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG214.AssetManager.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Desktop computer tower",
                            Manufacturer = "Dell",
                            Model = "PowerEdge T340",
                            SerialNumber = "D12L34",
                            TagNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Description = "All-in-one desktop computer",
                            Manufacturer = "HP",
                            Model = "Pavillion 27\" All-in-One",
                            SerialNumber = "H45P67",
                            TagNumber = "102"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Description = "Laptop computer",
                            Manufacturer = "Acer",
                            Model = "Swift 7",
                            SerialNumber = "A89C01",
                            TagNumber = "103"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            Description = "Widescreen computer monitor",
                            Manufacturer = "Acer",
                            Model = "21.5\" B7 Professional",
                            SerialNumber = "A23C45",
                            TagNumber = "201"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 2,
                            Description = "Ultra-widescreen computer monitor",
                            Manufacturer = "LG",
                            Model = "34\" UltraWide QHD",
                            SerialNumber = "L67G89",
                            TagNumber = "202"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 2,
                            Description = "4k computer monitor",
                            Manufacturer = "HP",
                            Model = "Envy 27",
                            SerialNumber = "H01P23",
                            TagNumber = "203"
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 3,
                            Description = "Multiline deskphone",
                            Manufacturer = "Avaya",
                            Model = "T7316E",
                            SerialNumber = "A45V67",
                            TagNumber = "301"
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 3,
                            Description = "Multiline deskphone",
                            Manufacturer = "Polycom",
                            Model = "VVX 411 IP",
                            SerialNumber = "P89C01",
                            TagNumber = "302"
                        },
                        new
                        {
                            Id = 9,
                            AssetTypeId = 3,
                            Description = "Multiline deskphone",
                            Manufacturer = "Cisco",
                            Model = "8861 IP",
                            SerialNumber = "C23C45",
                            TagNumber = "303"
                        });
                });

            modelBuilder.Entity("CPRG214.AssetManager.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CPRG214.AssetManager.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.AssetManager.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
